name: Add Label on Issue Movement

on:
  issues:
    types: [edited]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue was moved to specific column
        run: |
          issue_number=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)
          column_name=$(jq -r '.changes.project_card.column_name.from' $GITHUB_EVENT_PATH)

          if [ "$column_name" = "In Progress" ]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.inertia-preview+json" \
              -d '{"labels": ["in progress"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels"
          fi
