name: Build Kit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build kit
        run: pnpm run build:kit
