name: Test Golf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.1'
      - name: Install dependencies
        run: |
          npm install -g pnpm@8.15.5
          pnpm install
      - name: Test
        run: pnpm test
